// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqyortugaoboxdfrwdwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxeW9ydHVnYW9ib3hkZnJ3ZHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTM4ODksImV4cCI6MjA2OTM4OTg4OX0.MzHyBjN5cCfcgVVZvg5NUi_esermrQ6wbO48I-52rhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});